version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run dev
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
  
  caddy:
    image: caddy:2.7.6
    container_name: caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - app