version: "3"
services:
  app:
    image: smyakishev/devops-for-programmers-project-74
    command: npm test
    build:
      context: .
      dockerfile: Dockerfile.production
    volumes:
      - ".:/app"
