version: "3"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile.production
    command: npm test
    image: smyakishev/devops-for-programmers-project-74
    volumes:
      - ./app:/app
  