version: "3"
services:
  db:
    image: postgres:16.2
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    command: bash -c 'sleep 3 && npm run test'
    image: smyakishev/devops-for-programmers-project-74
    depends_on:
      - db

volumes:
  pgdata:
    external: false
