version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    command: bash -c "sleep 5 && npm test"
    image: smyakishev/devops-for-programmers-project-74
    volumes:
      - ./app:/app
  