name: push-workflow

on:
  push:
    branches:
      - '**'

jobs: 
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run tests
        run: make ci
      
      - name: Build prod
        run: make build_prod

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: smyakishev/devops-for-programmers-project-74:latest